language: node_js
node_js:
- '6'

services:
- mongodb

cache:
  directories:
    - node_modules

deploy:
- provider: s3
  access_key_id: AKIAI6WIA7NNUNTO3YLA
  secret_access_key:  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 
  local_dir: buildpun/
  skip_cleanup: true
  on: &2
    repo: https://github.com/sahil2311/node
  bucket: buildpun
  region: Oregon
- provider: codedeploy
  access_key_id: AKIAI6WIA7NNUNTO3YLA
  secret_access_key: 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
  bucket: buildpun
  key: latest.zip
  bundle_type: zip
  application: test
  deployment_group: test
  region: 
  on: *2

script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip..test
